"""
State type definitions for the LangGraph research graph.

Defines ResearchState (top-level graph state) and Subtask (individual
research unit) as TypedDicts for type-safe state management across nodes.

Usage:
    from src.graph.state import ResearchState, Subtask
    state: ResearchState = {
        "original_query": "NVIDIA",
        "subtasks": [],
        "current_subtask_idx": 0,
        "notes": [],
        "retry_count": 0,
        "max_retries": 3,
        "final_report": "",
        "errors": [],
    }
"""

from typing import TypedDict


class Subtask(TypedDict):
    """A single research subtask within the competitive analysis.

    Attributes:
        id: Unique integer identifier within the subtask list.
        description: Human-readable description of what to research.
        search_query: Optimized web search query for this subtask.
        status: Current state — pending, in_progress, done, or failed.
        result: Summarized research result text (populated after completion).
    """

    id: int
    description: str
    search_query: str
    status: str  # "pending" | "in_progress" | "done" | "failed"
    result: str


class ResearchState(TypedDict):
    """Complete state of a competitive analysis research run.

    Passed through all graph nodes; each node reads and writes relevant fields.

    Attributes:
        original_query: The company or topic the user wants analyzed.
        subtasks: List of subtasks generated by the planner.
        current_subtask_idx: Index of the subtask currently being processed.
        notes: Accumulated research notes (one per completed subtask).
        retry_count: Number of retries attempted for the current subtask.
        max_retries: Maximum allowed retries before skipping a subtask.
        final_report: Assembled Markdown report (populated by synthesizer).
        errors: List of error messages encountered during execution.
    """

    original_query: str
    subtasks: list[Subtask]
    current_subtask_idx: int
    notes: list[str]
    retry_count: int
    max_retries: int
    final_report: str
    errors: list[str]