export const mockCompanies = {
  openai: {
    name: 'OpenAI',
    industry: 'Artificial Intelligence',
    founded: '2015',
    hq: 'San Francisco, CA',
    employees: '1,500+',
    recentFunding: '$6.6B (Oct 2024)',
    valuation: '$90B+',
    tags: ['AI/ML', 'LLM', 'Enterprise SaaS'],
    sentimentScore: 78,
    sentimentBreakdown: { positive: 65, neutral: 22, negative: 13 },
    news: [
      { title: 'OpenAI launches GPT-4o with real‑time vision & voice', desc: 'Major multimodal model upgrade shipping across all tiers.', date: '3 days ago' },
      { title: 'Closed $6.6B funding round at $157B valuation', desc: 'Thrive Capital led the round…', date: '1 week ago' },
    ],
    growthRate: '+210%',
    marketPos: '#1 in LLM APIs',
    hiringTrend: { openRoles: 340 },
  },
  stripe: {
    name: 'Stripe',
    industry: 'Financial Technology',
    founded: '2010',
    hq: 'San Francisco, CA & Dublin, Ireland',
    employees: '8,000+',
    recentFunding: '$6.5B (2023)',
    valuation: '$70B+',
    tags: ['Fintech', 'Payments', 'API‑first'],
    sentimentScore: 82,
    sentimentBreakdown: { positive: 70, neutral: 20, negative: 10 },
    news: [
      { title: 'Stripe launches embedded checkout with AI fraud detection', desc: 'New checkout flow reduces drop‑off by 18% with built‑in Radar AI.', date: '4 days ago' },
    ],
    growthRate: '+35%',
    marketPos: '#1 Online Payments',
    hiringTrend: { openRoles: 520 },
  },
  figma: {
    name: 'Figma',
    industry: 'Design Software',
    founded: '2012',
    hq: 'San Francisco, CA',
    employees: '1,200+',
    recentFunding: 'Independent',
    valuation: '$20B (Adobe deal)',
    tags: ['Design', 'Collaboration', 'SaaS'],
    sentimentScore: 88,
    sentimentBreakdown: { positive: 75, neutral: 18, negative: 7 },
    news: [],
    growthRate: '+45%',
    marketPos: '#1 Collaborative Design',
    hiringTrend: { openRoles: 180 },
  },
};
